### ISSUE TITLE
$app['config']['root_urlpath'] を使用しないようにする

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/eccube-api#55]
対象：v0-beta-1.0.0
ファイル：EccubeApiController.php

`$app['config']['root_urlpath'].'/plugin/api/assets` のように$app['config']['root_urlpath']を使用している箇所があるが、/html/Pluginフォルダの取得には `$app['config']['plugin_urlpath']` を利用するようにする。

**Comment by nanasess** [comment]
#57 で対応
